resources:
  NovaComputeConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        nova:
          compute_driver: { get_input: nova_compute_driver }
          compute_libvirt_type: { get_input: nova_compute_libvirt_type }
          db: {get_input: nova_dsn}
          debug: {get_param: Debug}
          host: {get_input: nova_api_host}
          public_ip: {get_input: nova_public_ip}
          service-password: {get_input: nova_password}
        ceilometer:
          db: {get_input: ceilometer_dsn}
          debug: {get_param: Debug}
          metering_secret: {get_input: ceilometer_metering_secret}
          service-password: {get_input: ceilometer_password}
          compute_agent: {get_input: ceilometer_compute_agent}
        snmpd:
          export_MIB: UCD-SNMP-MIB
          readonly_user_name: {get_input: snmpd_readonly_user_name}
          readonly_user_password: {get_input: snmpd_readonly_user_password}
        glance:
          debug: {get_param: Debug}
          host: {get_input: glance_host}
          port: {get_input: glance_port}
          protocol: {get_input: glance_protocol}
        keystone:
          debug: {get_param: Debug}
          host: {get_input: keystone_host}
        neutron:
          debug: {get_param: Debug}
          flat-networks: {get_input: neutron_flat_networks}
          host: {get_input: neutron_host}
          ovs_db: {get_input: neutron_dsn}
          l3_ha: {get_input: neutron_l3_ha}
          ovs:
            local_ip: {get_input: neutron_local_ip}
            tenant_network_type: {get_input: neutron_tenant_network_type}
            tunnel_types: {get_input: neutron_tunnel_types}
            network_vlan_ranges: {get_input: neutron_network_vlan_ranges}
            bridge_mappings: {get_input: neutron_bridge_mappings}
            enable_tunneling: {get_input: neutron_enable_tunneling}
            physical_bridge: {get_input: neutron_physical_bridge}
            public_interface: {get_input: neutron_public_interface}
          service-password: {get_input: neutron_password}
        admin-password: {get_input: admin_password}
        rabbit:
          host: {get_input: rabbit_host}
          username: {get_input: rabbit_username}
          password: {get_input: rabbit_password}
        live-update:
          host: {get_input: live_update_host}
          username: {get_input: live_update_username}
          password: {get_input: live_update_password}
          tenant-name: {get_input: live_update_tenant_name}
          base_image_id: {get_input: nova_image}
          live_update_image_id: {get_input: live_update_compute_image}
        ntp:
          servers:
              - {server: {get_input: ntp_server}, fudge: "stratum 0"}
  NovaComputePassthrough:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config: {get_input: passthrough_config}
  NovaComputePassthroughSpecific:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config: {get_input: passthrough_config_specific}
