Parameters:
  # NOTE(rpodolyaka): limitation of tuskar-api, see https://bugs.launchpad.net/tuskar/+bug/1235236
  OvercloudAdminPassword:
    Default: unset
    Description: The password of admin user of the overcloud (required by some services in the under cloud)
    Type: String
  OvercloudKeystoneHost:
    Description: The Overcloud Host running Keystone
    Type: String
Resources:
  undercloudTuskarVm:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      OpenStack::Role: undercloudConfig
      tuskar:
        db: mysql://tuskar:unset@127.0.0.1/tuskar?charset=utf8
        user: admin
        tenant_name: admin
        password: {Ref: AdminPassword}
        overcloud-admin-password: {Ref: OvercloudAdminPassword}
        overcloud-keystone-host: {Ref: OvercloudKeystoneHost}
