Parameters:
  IronicPassword:
    Type: String
    Description: Ironic password for keystone access
    NoEcho: true
  NeutronPublicInterface:
    Default: eth0
    Description: What interface to bridge onto br-ex for network nodes.
    Type: String
  PowerSSHPrivateKey:
    Description: Private key for using to ssh to a virtual power host.
    Type: String
    NoEcho: true
Resources:
  undercloudConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      ironic:
        db: mysql://ironic:unset@127.0.0.1/ironic
        service-password:
          Ref: IronicPassword
        virtual_power_ssh_key:
          Ref: PowerSSHPrivateKey
      nova:
        compute_hostname: undercloud
        compute_driver: ironic.nova.virt.ironic.driver.IronicDriver
        compute_manager: ironic.nova.compute.manager.ClusteredComputeManager
        db: mysql://nova:unset@127.0.0.1/nova
        default_ephemeral_format: ext4
        host: 127.0.0.1
        metadata-proxy: false
        tuning:
          ram_allocation_ratio: 1.0
          reserved_host_memory_mb: 0
        service-password:
          Ref: NovaPassword
